[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = ['cpp']

[[plugins]]
#rust用
repo = 'rust-lang/rust.vim'
on_ft = ['rust']

[[plugins]]
#rust用
repo = 'sebastianmarkow/deoplete-rust' 
hook_add = '''
      let g:deoplete#sources#rust#racer_binary='/Users/yataka/.cargo/bin/racer'
      let g:deoplete#sources#rust#rust_source_path='/Users/yataka/rust/src'
'''
on_ft = ['rust']

[[plugins]]
#python用
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'deoplete-plugins/deoplete-jedi'
hook_host_source = '''
      let g:jedi#completions_command = "<C-N>"
'''
on_ft = ['python']

[[plugins]]
#ruby用
repo = 'takkii/totolot'
on_ft = ['ruby']

[[plugins]]
#ruby用
repo = 'takkii/ruby-dictionary3' 
hook_host_source = '''
     let g:ruby_host_prog = '/Users/yataka/.rbenv/versions/2.6.3/bin/neovim-ruby-host'
'''
on_ft = ['ruby']

[[plugins]]
repo = 'copy/deoplete-ocaml'
on_ft = ['ocaml']

[[plugins]]
repo = 'lervag/vimtex'
hook_source = '''
let g:vimtex_compiler_progname = 'nvr'
call deoplete#custom#var('omni', 'input_patterns', {
          \ 'tex': g:vimtex#re#deoplete
          \})
'''
on_ft = ['tex']


